### ISSUE TITLE
disconnect call does not end call completely

### ISSUE THREAD

**Issue by karthikgollapudi** [twilio/video-sample-ios-capture-render#10]
Calling `self.conversation!.disconnect()` does not appear to properly end the call.

I execute the above line when ending a call, and ensure that conversation is not `nil`. Then when attempting to launch another call, I get these errors:

`Error creating conversation: Optional(Error Domain=signal.sdk.domain.error Code=202 "Maximum number of active conversations reached." UserInfo={NSLocalizedRecoverySuggestion=End active conversations by calling disconnect., NSLocalizedDescription=Maximum number of active conversations reached., NSLocalizedFailureReason=Max conversation limit is 1})`

`2016-05-14 16:24:12.038 Ambivio IOS[28223:7316536] TwilioConversations:[Platform]:Fatal runtime capture error: Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x137a461b0 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-12780), NSLocalizedDescription=The operation could not be completed}, code -11800`

Sometimes after disconnecting a call and closing the view, an audio connection persists between both devices. I would think this is related to the same issue? Has anyone else seen these issues?

**Comment by karthikgollapudi** [comment]
Issue is due to a `NSTimer` that had a strong reference to it when hanging up the first call. By calling `.invalidate()` on the timer, the view was properly removed from memory. Now incoming calls load a new view.

**Comment by ptankTwilio** [comment]
As discussed over the email I was not reproduce the issue either. 
Thanks for closing the ticket. Let me know if you run through any other issue.

**Comment by alifarhan2532** [comment]
i am having the same issue any solution for this issue

**Comment by karthikgollapudi** [comment]
Check if you have any timers running - those will prevent the view from being destroyed. As long as the view is still alive, there are likely still video connection resources connected in the background. That was my issue.

By invalidating the timers when disconnecting a call, the View was able to be dismissed properly.
