### ISSUE TITLE
How to set remote view as a full screen view?

### ISSUE THREAD

**Issue by pradeep-chauhan** [twilio/video-sample-ios-capture-render#11]
i want to set remote view display as full screen. right now its showing in center.

**Comment by ceaglest** [comment]
@pradeep-chauhan Sorry for the late response. If you didn't already contact support about this issue, then I should mention that cropping video to fill the screen is not yet supported with our renderers. We have heard a number of requests for this feature and hope to add support for it in a future release of our iOS SDK.

**Comment by darkredz** [comment]
@ceaglest is the video still unable to fill up the screen? What is the timeline to support this feature for ios sdk?

**Comment by ptankTwilio** [comment]
Hi @darkredz 

We have released Room based, I recommend you migrate your app to use the Room based Video SDK. The Room based video SDK has more features and it is more stable. 

Download link: https://www.twilio.com/docs/api/video/download-video-sdks#ios-sdk
Link to change logs: https://www.twilio.com/docs/api/video/changelogs/ios
