### ISSUE TITLE
Saving Local Video track in SD-Card

### ISSUE THREAD

**Issue by AnkanDey88** [twilio/video-sample-ios-capture-render#18]
I am using twilio for video multiparty chat. Now I want to save the local video track into SD-Card. Anybody please drop any suggestion.

**Comment by ceaglest** [comment]
Hi @AnkanDey88,

First off, this repo is for a sample app using our deprecated Conversations SDK. Please don't use it as the service is about to be retired next month. I would point you to our newer Video SDK.

https://www.twilio.com/docs/api/video
https://github.com/twilio/video-quickstart-swift

More specifically, if you want to capture a still image or video from a TVICameraCapturer you should have a look at these issues:

https://github.com/twilio/video-quickstart-swift/issues/142
https://github.com/twilio/video-quickstart-swift/issues/123

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @AnkanDey88,

I hope you were able to get the help you needed in `video-quickstart-swift`. I'm going to close this issue out, but feel free to raise more questions in the issues I linked you to.

Regards,
Chris Eagleston
